export const PRODUCTS = [
    {
        id: 0,
        category: 'accessories',
        brand: 'Zee Dog',
        itemName: 'Harness',
        price: '200',
        image: require('../assets/images/products/accessory.jpg'),
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    },
    {
        id: 1,
        category: 'food',
        brand: 'Greenies',
        itemName: 'Dental Treat',
        price: '1000',
        image: require('../assets/images/products/greenies.jpg'),
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    },
    {
        id: 2,
        category: 'toys',
        brand: 'Zee Dog',
        itemName: 'Harness',
        price: '420',
        image: require('../assets/images/products/toy.jpg'),
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    },
    {
        id: 3,
        favourite: true,
        category: 'accessories',
        brand: 'Paws Co.',
        itemName: 'Bandana',
        price: '500',
        image: require('../assets/images/products/bandana.jpg'),
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    },
    {
        id: 4,
        favourite: true,
        category: 'toys',
        brand: 'Kong',
        itemName: 'Alligator Plushie',
        price: '200',
        image: require('../assets/images/products/plush.jpg'),
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    },
    {
        id: 5,
        favourite: true,
        category: 'food',
        brand: "Lily's Kitchen",
        itemName: 'Bedtime Biscuit',
        price: '200',
        image: require('../assets/images/products/food.jpg'),
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    },
    {
        id: 6,
        category: 'accessories',
        brand: 'Earth Rated',
        itemName: 'Poop Bags',
        price: '200',
        image: require('../assets/images/products/poopbag.jpg'),
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    },
    {
        id: 6,
        category: 'toys',
        brand: 'Pet Co.',
        itemName: 'Duck Plushie',
        price: '฿200',
        image: require('../assets/images/products/duck.jpg'),
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    },
    {
        id: 7,
        favourite: true,
        category: 'food',
        brand: 'Himalayan Yak Cheese',
        itemName: 'Himalayan Cheese',
        price: '2500',
        image: require('../assets/images/products/treat.jpg'),
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    }
];